name: Build, Release, and Update JSON

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Verify Secret Access
        run: echo "Secret INDAK_HTS is set correctly"
        env:
          GITHUB_TOKEN: ${{ secrets.INDAK_HTS }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          ini-file: production

      - name: Validate PHP
        run: |
          php -l *.php || true
          php -l core/*.php || true
          php -l admin/*.php || true
          php -l api/*.php || true

      # Create the ZIP file
      - name: Create ZIP
        run: |
          zip -r wheelpros-hts-${{ github.ref_name }}.zip . -x "*.git*" -x ".github*" -x "node_modules/*" -x "*.log" -x "tests/*" -x "*.md"

      # Upload the ZIP file as a release asset
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: wheelpros-hts-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.INDAK_HTS }}

      - name: Generate Version JSON
        run: |
          VERSION=${{ github.ref_name }}
          cat <<EOF > version.json
          {
            "name": "WheelPros Integration for HTS",
            "slug": "wheelpros-hts",
            "version": "${VERSION#v}",
            "download_url": "https://github.com/${{ github.repository }}/releases/download/${VERSION}/wheelpros-hts-latest.zip",
            "requires": "5.0",
            "tested": "6.3",
            "requires_php": "7.4"
          }
          EOF

      # Push the version.json file to the version-file branch
      - name: Push Version JSON to version-file Branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -B version-file
          git add version.json
          git commit -m "Update version.json for ${VERSION}"
          git push origin version-file --force
