name: Build, Release, and Update JSON

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          ini-file: production

      - name: Extract version from tag
        id: version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update Version in PHP File
        run: |
          sed -i "s/^.*Version:.*$/ * Version:           ${{ env.VERSION }}/" wheelpros-hts.php
          sed -i "s/define( 'WHEELPROS_HTS_VERSION'.*/define( 'WHEELPROS_HTS_VERSION', '${{ env.VERSION }}' );/" wheelpros-hts.php

      - name: Update CHANGELOG.md
        run: |
          echo "## [${{ env.VERSION }}] - $(date +'%Y-%m-%d')" >> CHANGELOG.md
          echo "- Automatically updated changelog for version ${{ env.VERSION }}" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          cat CHANGELOG.md

      - name: Commit Version and Changelog Updates
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add wheelpros-hts.php CHANGELOG.md
          git commit -m "Update version to ${{ env.VERSION }} and changelog"
          git push origin main

      # Create the ZIP file with the version tag
      - name: Create ZIP
        run: |
          zip -r wheelpros-hts-${{ env.VERSION }}.zip . -x "*.git*" -x ".github*" -x "node_modules/*" -x "*.log" -x "tests/*" -x "*.md"

      # Upload the ZIP file as a release asset
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: wheelpros-hts-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Version JSON
        run: |
          cat <<EOF > version.json
          {
            "name": "WheelPros Integration for HTS",
            "slug": "wheelpros-hts",
            "version": "${{ env.VERSION }}",
            "download_url": "https://github.com/${{ github.repository }}/releases/download/v${{ env.VERSION }}/wheelpros-hts-latest.zip",
            "requires": "5.0",
            "tested": "6.3",
            "requires_php": "7.4"
          }
          EOF

      - name: Push Version JSON to version-file Branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -B version-file
          git add version.json
          git commit -m "Update version.json for ${{ env.VERSION }}"
          git push origin version-file --force
