name: Build, Release, and Update JSON

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          ini-file: production

      - name: Validate PHP
        run: |
          php -l wheelpros-hts/*.php || true
          php -l wheelpros-hts/core/*.php || true
          php -l wheelpros-hts/admin/*.php || true
          php -l wheelpros-hts/api/*.php || true

        # Create the ZIP file
      - name: Create ZIP
        run: |
          zip -r wheelpros-hts-v${{ github.ref_name }}.zip wheelpros-hts -x "*.git*" -x "*.github*" -x "node_modules/*" -x "*.log"

      # Upload the ZIP file as a release asset
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: wheelpros-hts-v${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Generate version JSON
      - name: Generate Version JSON
        run: |
          VERSION=${{ github.ref_name }}
          cat <<EOF > version.json
          {
            "name": "WheelPros Integration for HTS",
            "slug": "wheelpros-hts",
            "version": "${VERSION#v}",
            "download_url": "https://github.com/${{ github.repository }}/releases/download/${VERSION}/wheelpros-hts-${VERSION}.zip",
            "requires": "5.0",
            "tested": "6.3",
            "requires_php": "7.4"
          }
          EOF

      # Commit and push version JSON to a branch
      - name: Commit Version JSON
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -B version-file
          mv version.json ./version.json
          git add version.json
          git commit -m "Update version.json for ${VERSION}"
          git push origin version-file --force
