name: Build, Release, and Update JSON

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          ini-file: production

      - name: Validate PHP
        run: |
          php -l *.php || true
          php -l core/*.php || true
          php -l admin/*.php || true

      # Extract version from plugin file for dynamic versioning
      - name: Extract Version
        id: version
        run: |
          if [ -f "harrys-wheelpros-importer.php" ]; then
            VERSION_NUM=$(grep -oP 'Version:\s*\K[\d.]+' harrys-wheelpros-importer.php || echo "1.8.0")
          else
            VERSION_NUM="1.8.0"
          fi
          VERSION="v${VERSION_NUM}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "version_num=${VERSION_NUM}" >> $GITHUB_OUTPUT
          echo "Detected version: ${VERSION}"

      # Create the ZIP file with the version from plugin file
      - name: Create ZIP
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          zip -r harrys-wheelpros-importer-${VERSION}.zip . \
            -x "*.git*" \
            -x ".github*" \
            -x "node_modules/*" \
            -x "*.log" \
            -x "tests/*" \
            -x "*.md" \
            -x "AUTO-UPDATE-SETUP.md"

      # Duplicate/rename the ZIP file to have a consistent filename
      - name: Duplicate ZIP
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          cp harrys-wheelpros-importer-${VERSION}.zip harrys-wheelpros-importer-latest.zip

      # Upload the ZIP file with the version tag as a release asset
      - name: Publish Release with Version Tag
        uses: softprops/action-gh-release@v1
        with:
          files: |
            harrys-wheelpros-importer-${{ steps.version.outputs.version }}.zip
            harrys-wheelpros-importer-latest.zip
          tag_name: ${{ steps.version.outputs.version }}
          name: "Release ${{ steps.version.outputs.version }}"
          body: |
            ## Harry's WheelPros Importer ${{ steps.version.outputs.version }}

            ### Installation
            1. Download the ZIP file below
            2. Upload to WordPress via Plugins > Add New > Upload Plugin
            3. Activate the plugin

            ### Features
            - Memory-efficient two-phase import system
            - Secure SFTP import from WheelPros servers
            - Manual CSV upload fallback
            - Real-time progress tracking
            - Automatic updates from GitHub

            **Download:** harrys-wheelpros-importer-${{ steps.version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Version JSON
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          VERSION_NUM="${{ steps.version.outputs.version_num }}"
          cat <<EOF > version.json
          {
            "name": "Harry's WheelPros Importer",
            "slug": "harrys-wheelpros-importer",
            "version": "${VERSION_NUM}",
            "download_url": "https://github.com/${{ github.repository }}/releases/download/${VERSION}/harrys-wheelpros-importer-${VERSION}.zip",
            "requires": "5.0",
            "tested": "6.7.1",
            "requires_php": "7.4",
            "author": "Alex Macpherson | Macpherson Designs",
            "author_homepage": "https://macphersondesigns.com",
            "sections": {
              "description": "Securely import WheelPros wheel data from CSV/JSON and display it as a custom post type with advanced filtering capabilities.",
              "installation": "1. Download the plugin ZIP file\\n2. Upload via WordPress Admin > Plugins > Add New > Upload Plugin\\n3. Activate the plugin\\n4. Configure SFTP settings in WheelPros Importer > Settings",
              "changelog": "See release notes at https://github.com/${{ github.repository }}/releases"
            },
            "banners": {
              "low": "",
              "high": ""
            },
            "icons": {
              "1x": "",
              "2x": ""
            }
          }
          EOF

      # Push the version.json file to the version-file branch
      - name: Push Version JSON to version-file Branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          VERSION="${{ steps.version.outputs.version }}"
          VERSION_NUM="${{ steps.version.outputs.version_num }}"

          # Try to fetch version-file branch, create if it doesn't exist
          git fetch origin version-file 2>/dev/null || echo "version-file branch doesn't exist yet"

          # Create or switch to version-file branch
          git checkout version-file 2>/dev/null || git checkout --orphan version-file

          # Clean working directory safely - remove tracked files
          git ls-files | xargs rm -f 2>/dev/null || true

          # Create version.json with extracted version
          cat <<EOF > version.json
          {
            "name": "Harry's WheelPros Importer",
            "slug": "harrys-wheelpros-importer",
            "version": "${VERSION_NUM}",
            "download_url": "https://github.com/${{ github.repository }}/releases/download/${VERSION}/harrys-wheelpros-importer-${VERSION}.zip",
            "requires": "5.0",
            "tested": "6.7.1",
            "requires_php": "7.4",
            "author": "Alex Macpherson | Macpherson Designs",
            "author_homepage": "https://macphersondesigns.com",
            "sections": {
              "description": "Securely import WheelPros wheel data from CSV/JSON and display it as a custom post type with advanced filtering capabilities.",
              "installation": "1. Download the plugin ZIP file\\n2. Upload via WordPress Admin > Plugins > Add New > Upload Plugin\\n3. Activate the plugin\\n4. Configure SFTP settings in WheelPros Importer > Settings",
              "changelog": "See release notes at https://github.com/${{ github.repository }}/releases"
            },
            "banners": {
              "low": "",
              "high": ""
            },
            "icons": {
              "1x": "",
              "2x": ""
            }
          }
          EOF

          # Create README for version branch
          cat <<EOF > README.md
          # Version File Branch
          This branch contains the version.json file used by the Plugin Update Checker.
          It is automatically updated by GitHub Actions when changes are pushed to main.
          EOF

          # Add and commit changes
          git add version.json README.md

          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update version.json for v${VERSION}"
            git push origin version-file
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
